version: '3.1'

networks:
  error-network:
      driver: bridge

volumes:
  esdata:
    driver: local

services:
  ruby:
    build:
      context: .
      dockerfile: docker/ruby/Dockerfile
    volumes:
      - ./docker/ruby/debugging:/opt/debugging
      - ./docker/ruby/ssh/sshd_config:/etc/ssh/sshd_config
      - ./docker/ruby/entrypoint.sh:/entrypoint.sh
      - ./src:/app
    networks:
      - error-network
    ports:
      - "3000:3000"
      - "2222:22"
    stdin_open: true
    tty: true
    entrypoint:
      - /entrypoint.sh
#    command: bundle exec rails s -p 3000 -b '0.0.0.0' -e development
#    command: bundle exec rdebug-ide --host '0.0.0.0' --port 1234 --dispatcher-port 26162 -- /app/bin/rails s -b '0.0.0.0' -p 3000 -e development
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./src/database/import:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=layers-app_development
      - MYSQL_USER=user
      - MYSQL_PASSWORD=root
    networks:
      - error-network
  redis:
    image: redis:3.2
    networks:
      - error-network
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 1s
      retries: 300
