version: '3.1'

networks:
  error-network:
      driver: bridge

volumes:
  esdata:
    driver: local

services:
  ruby:
    build:
      context: .
      dockerfile: docker/ruby/Dockerfile
    volumes:
      - ./src:/home/app/lol
      - /home/app/lol/node_modules
    networks:
      - error-network
    ports:
      - "3000:3000"
      - "2222:22"
    stdin_open: true
    tty: true
    command: bundle exec rails s -p 3000 -b '0.0.0.0' -e development
    depends_on:
      - mysql
#    healthcheck:
#      test: ["CMD", "curl", "http://localhost:3000"]
#      interval: 2s
#      timeout: 20s
#      retries: 2
    labels:
      - maintainer="jordi@error.agency"
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./src/database/import:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=layers-app_development
      - MYSQL_USER=user
      - MYSQL_PASSWORD=root
    networks:
      - error-network
    labels:
      - maintainer="jordi@error.agency"
  redis:
    image: redis:3.2
    networks:
      - error-network
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 1s
      retries: 300
    labels:
      - maintainer="jordi@error.agency"
