version: '3.3'

networks:
  error-network:
      driver: bridge

volumes:
  esdata:
    driver: local

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.1
    networks:
      - error-network
    ports:
      - "9200:9200"
    environment:
      LOGSPOUT: 'ignore'
      ES_JAVA_OPTS: '-Xms1024m -Xmx1024m'
      bootstrap.memory_lock: 'false'
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - esdata:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD", "curl", "-SsfL", "127.0.0.1:9200/_cat/health?h=status"]
      interval: 1s
      timeout: 1s
      retries: 300