version: '3.2'

networks:
  error-network:
      driver: bridge

volumes:
  esdata:
    driver: local

services:
  elasticsearch:
    build:
      context: .
      dockerfile: docker/elasticsearch/Dockerfile
    networks:
      - error-network
    ports:
      - "9200:9200"
      - "8080:8080"
    environment:
      LOGSPOUT: 'ignore'
      ES_JAVA_OPTS: '-Xms1024m -Xmx1024m'
      bootstrap.memory_lock: 'false'
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - esdata:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD", "curl", "-SsfL", "127.0.0.1:9200/_cat/health?h=status"]
      interval: 60s
      timeout: 1s
      retries: 10

