version: '3'

networks:
  erra:

services:
  ruby:
    build:
      context: .
      dockerfile: docker/ruby/Dockerfile
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    networks:
      erra:
  mysql:
    ports:
      - "3306:3306"
    image: mysql:5.7
    volumes:
      - db-data:/var/lib/mysql
      - ./data/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=layers-app_development
      - MYSQL_USER=user
      - MYSQL_PASSWORD=root
    networks:
      erra:

volumes:
  db-data:
    driver: local