default: &default
  adapter: mysql2
  host: 127.0.0.1
  port: 3306
  username: root
  password: root

development:
  <<: *default
  database: layers_development

test:
  <<: *default
  database: layers_development

production:
  <<: *default
  database: db/production.sqlite3
