AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
    - '**/Gemfile'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'app/jobs/**/*'

    - 'test/**/*'
    - 'node_modules/**/*'
    - 'bin/**/*'
    - !ruby/regexp /old_and_unused\.rb$/
Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/LineLength:
  Max: 200
